#ifndef GUARD_CONSTANTS_RANDOM_MON_GENERATION_H
#define GUARD_CONSTANTS_RANDOM_MON_GENERATION_H

enum
{
    SPECIES_GENERATOR_NORMAN_GIFT,
    RANDOM_SPECIES_OPTIONS_COUNT,
};

enum
{
    RANDOM_ITEM_OPTIONS_COUNT,
};

#endif // GUARD_CONSTANTS_RANDOM_MON_GENERATION_H
